/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 aiGalleryUsed.glb 
*/

import React, { useRef } from 'react'
import { Clone, Html, useGLTF ,Image} from '@react-three/drei'
import { Slider } from 'antd'


export const Scene=(props)=> {
  const { nodes, materials } = useGLTF('/aiGalleryUsed.glb')
  const image=[
    'https://telegraph-image-3k8.pages.dev/file/90ba9fde0683d717945cb.jpg',
    'https://telegraph-image-3k8.pages.dev/file/adcc393d150a8c16e72a7.jpg',
    'https://telegraph-image-3k8.pages.dev/file/91f9834cd80e250c7b927.jpg',
    'https://telegraph-image-3k8.pages.dev/file/d6de2d827d8959df78ed9.jpg',
    'https://telegraph-image-3k8.pages.dev/file/d644d63ad86eed76ea71c.jpg',
    'https://telegraph-image-3k8.pages.dev/file/2054b3cf3f0975efa1de9.jpg',
    'https://telegraph-image-3k8.pages.dev/file/d206e5c5c92a3535b61ca.jpg',
    'https://telegraph-image-3k8.pages.dev/file/a34baf1c73c3c13dcad64.jpg',
    'https://telegraph-image-3k8.pages.dev/file/bb15f7d1e0a481702478d.jpg',
    'https://telegraph-image-3k8.pages.dev/file/07fb519451ae62c4570bd.jpg',
    'https://telegraph-image-3k8.pages.dev/file/f87b9fd9305890ab158cf.jpg',
    'https://telegraph-image-3k8.pages.dev/file/57ca8c637ddcc629bfa4e.jpg',
    '','','','',

  ]
  return (
    <group {...props} dispose={null}>
      {/* <ImageFrame/> */}
      {/* 中间那排 */}
      <Clone object={nodes['Cube007']} />
      <Clone object={nodes['Cube008']} />
      <Clone object={nodes['Cube009']} />
      {/* <ImageFrame object={nodes['Cube010']} imgUrl={image[0]}/> */}
      <ImageFrame object={nodes['Cube002']} imgUrl={image[0]}/>
      <ImageFrame object={nodes['Cube011']} imgUrl={image[1]}/>
      <ImageFrame object={nodes['Cube012']} imgUrl={image[2]}/>
      
      {/* 楼梯旁边的 */}
      <ImageFrame object={nodes['Cube006']} imgUrl={image[3]}/>
      
      {/* 楼梯 */}
      <Clone object={nodes['Cube005']}/>
      <Clone object={nodes['Cube013']}/>
      
      {/* 后面 */}
      <ImageFrame object={nodes['Cube001']} imgUrl={image[4]}/>
      <ImageFrame object={nodes['Cube014']} imgUrl={image[5]}/>
      <ImageFrame object={nodes['Cube015']} imgUrl={image[6]}/>
      <ImageFrame object={nodes['Cube016']} imgUrl={image[7]}/>
      <ImageFrame object={nodes['Cube017']} imgUrl={image[8]}/>
      <ImageFrame object={nodes['Cube018']} imgUrl={image[9]}/>
      <ImageFrame object={nodes['Cube019']} imgUrl={image[10]}/>

      {/* 旁边 */}
      <ImageFrame object={nodes['Cube020']} imgUrl={image[12]}/>
      <ImageFrame object={nodes['Cube021']} imgUrl={image[0]}/>
      <ImageFrame object={nodes['Cube022']} imgUrl={image[0]}/>
      
      {/* 墙壁 */}
      <Clone object={nodes['Cube_1']} />
      {/* 地面 */}
      <Clone object={nodes['Cube_2']} />

      {/* <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[1.832, 1.032, 0.139]} /> */}
      {/* 
            <mesh geometry={nodes.Cube007.geometry} material={materials.blackWall} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.blackWall} position={[1.825, 0, 0]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.blackWall} position={[3.65, 0, 0]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.blackWall} position={[5.475, 0, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-3.141, 1.034, -3.717]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.blackWall} position={[-5, 1.514, -3.401]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.blackWall} position={[-5, 1.514, -3.401]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0, 1.032, 0.139]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[3.665, 1.032, 0.139]} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[0, 1.032, -0.137]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[1.832, 1.032, -0.137]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[3.665, 1.032, -0.137]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-1.544, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[0.288, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[2.12, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[3.953, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[-4.987, 1.032, 3.352]} />
      <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-4.987, 1.032, 1.52]} />
      <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-4.987, 1.032, -0.312]} /> */}
      {/* <mesh geometry={nodes.Cube_1.geometry} material={materials.blackWall} /> */}
      {/* <mesh geometry={nodes.Cube_2.geometry} material={materials.Material} /> */}
      
      {/* sofa&sofa2 */}
      {/* <group position={[4.646, 0.464, 3.802]} rotation={[0, -1.571, 0]} scale={1.216}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Cinema_Sof} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Cinema_Sof_1} />
      </group> */}
           {/* <group position={[4.626, -0.174, 3.707]} rotation={[0, -1.571, 0]} scale={0.407}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Couch_Medium1_1.geometry} material={materials.Couch_Blue} />
          <mesh geometry={nodes.Couch_Medium1_2.geometry} material={materials.Black} />
        </group>
      </group> */}
    </group>
  )
}

useGLTF.preload('/aiGalleryUsed.glb')


const ImageFrame = ({ object, imgUrl, intensity = 300, rotation = 1, ...props }) => {
  return(
<>
    <Clone object={object} {...props} >
    <Image url='/image/20240503-025135.jpg' />
 
    </Clone>
    </>
)}