/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 aiGalleryUsed.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/aiGalleryUsed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.626, -0.174, 3.707]} rotation={[0, -1.571, 0]} scale={0.407}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Couch_Medium1_1.geometry} material={materials.Couch_Blue} />
          <mesh geometry={nodes.Couch_Medium1_2.geometry} material={materials.Black} />
        </group>
      </group>
      <mesh geometry={nodes.Cube007.geometry} material={materials.blackWall} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.blackWall} position={[1.825, 0, 0]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.blackWall} position={[3.65, 0, 0]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.blackWall} position={[5.475, 0, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-3.141, 1.034, -3.717]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.blackWall} position={[-5, 1.514, -3.401]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.blackWall} position={[-5, 1.514, -3.401]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0, 1.032, 0.139]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[1.832, 1.032, 0.139]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[3.665, 1.032, 0.139]} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[0, 1.032, -0.137]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[1.832, 1.032, -0.137]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[3.665, 1.032, -0.137]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-1.544, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[0.288, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[2.12, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[3.953, 1.032, -4.995]} />
      <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[-4.987, 1.032, 3.352]} />
      <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-4.987, 1.032, 1.52]} />
      <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-4.987, 1.032, -0.312]} />
      <group position={[4.646, 0.464, 3.802]} rotation={[0, -1.571, 0]} scale={1.216}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Cinema_Sof} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Cinema_Sof_1} />
      </group>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.blackWall} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/aiGalleryUsed.glb')
